language: c
os:
 - linux
 - osx
dist: bionic
arch:
 - amd64
git:
  quiet: true
branches:
  only:
    - master
before-script:
  - sudo apt-get -qq update
  - sudo apt-get -y install libc6-dev
script:
  - make Q=strace c2mir-bootstrap-test
