name: build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      if: runner.os != 'Windows'
      run: make
    - name: cmake
      if: runner.os == 'Windows'
      run: |
        cmake -G 'Visual Studio 16 2019' -A x64
        cmake --build .
