name: test

on: [push]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: make test
