name: test

on: [push]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: update
      run: apt update -y
    - uses: actions/checkout@v1
    - name: make test
      run: make test
